[project]
name = "python-tokenize"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "tiktoken>=0.8.0",
    "tokenizers>=0.21.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
